site_name: LiuTianBa7 's Blog
site_url: https://liutianba7.github.io # 建议加上你的域名
repo_url: https://github.com/liutianba7/liutianba7.github.io
repo_name: blog
edit_uri: edit/main/docs/  # 允许直接从网页跳转到 GitHub 编辑源码



nav:
  - Welcome: index.md
  - Java:
    - ssm: ./java/02_Frameworks/ssm.md
    - springboot: ./java/02_Frameworks/springboot.md
    - maven: ./java/01_Java_Core/maven.md
    - juc: ./java/01_Java_Core/juc.md
  - Python:
      - Env:
          - conda: ./python/01_env/conda.md
          - uv: ./python/01_env/uv.md
          - jupyter: ./python/01_env/jupyter.md
      - Basic:
          - python_basic: ./python/02_basic/python基础.md
      - Others:
          - requests: ./python/03_others/requests.md
          - pandas: ./python/03_others/pandas.md
          - numpy: ./python/03_others/numpy.md
          - pytest: ./python/03_others/pytest.md
      - Web:
          - fastapi: ./python/04_web/fastapi.md
      - AI:
          - langchain: ./python/05_ai/langchain.md
          - pytorch: ./python/05_ai/pytorch.md
          - ollama: ./python/05_ai/ollama.md
  - Frontend:
      - js: ./frontend/js.md
      - vue2: ./frontend/vue2.md
      - vue3: ./frontend/vue3.md

  - Code-Notes:
      - 概览: ./code-notes/index.md
      - Java:
          - 并发编程: ./code-notes/java/concurrent.md
          - 设计模式: ./code-notes/java/design-patterns.md
      - Python:
          - ai: ./code-notes/python/ai.md
      - Algorithm:
          - 算法模板: ./code-notes/algorithm/template.md

  - Bagu:
      - 复习路线: ./interview/index.md
      - Java:
          - java基础: ./interview/java/java基础.md
          - java集合: ./interview/java/java集合.md
          - juc: ./interview/java/juc.md
          - jvm: ./interview/java/jvm.md
          - ssm: ./interview/java/ssm.md
          - springboot|cloud: ./interview/java/springboot+Cloud.md
          - 设计模式: ./interview/java/设计模式.md
      - Database:
          - mysql: ./interview/database/mysql.md
          - redis: ./interview/database/redis.md
      - Middleware:
          - elasticsearch: ./interview/middleware/es.md
          - rabbitmq: ./interview/middleware/rmq.md
          - seata: ./interview/middleware/seata.md
      - Python:
          - python: ./interview/python/python.md
#  - Journal:
#      - 202602: ./journal/2026-02.md
  - Tools:
      - git: ./tools/git.md
      - docker: ./tools/docker.md
  - Middleware:
    - mysql 基础: ./middleware/mysql基础.md
    - mysql 高级: ./middleware/mysql高级.md
    - redis: ./middleware/redis.md
    - minio: ./middleware/minio.md
  - Linux:
      - basic: ./linux/basic.md

use_directory_urls: false

plugins:
  - search


theme:
  name: material
  language: zh
  # 1. 调色盘：支持深浅模式自动切换
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white    # 极简白背景 网站头部颜色
      accent: indigo    # 链接和交互色
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black    # 深色模式
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式

  # 2. 界面细节优化
  features:
    - navigation.tabs              # 顶部横向菜单栏（适合分类多时）
    - navigation.tracking          # 滚动时自动定位侧边栏
    - navigation.top               # 返回顶部按钮
    - search.suggest               # 搜索输入补全
    - search.highlight             # 搜索结果高亮
    - content.code.copy            # 代码块一键复制按钮

  icon:
    logo: material/cat
    repo: fontawesome/brands/github  # 这一行是关键，强制指定右上角为小猫
    favicon: material/cat          # 浏览器标签页的小图标

copyright: |
  Copyright &copy; 2026 LiuTianBa7 

markdown_extensions:
#  - toc:
#      toc_depth: 4              # 目录显示到四级标题
#      permalink: true           # 标题旁显示永久链接图标
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:   # 数学公式支持
      generic: true


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/reading-progress.js

extra_css:
  - stylesheets/extra.css